### ISSUE TITLE
LanguageToolError: http://127.0.0.1:8081/v2/: timed out

### ISSUE THREAD

**Issue by akshaytheau** [jxmorris12/language_tool_python#10]
I faced this error while running tool.check function on a piece of text . Can anyone please guide me here ?

**Comment by jxmorris12** [comment]
Hi @akshaytheau -- can you send me the full command that you ran? What was the text, and how long?

**Comment by akshaytheau** [comment]
Hey @jxmorris12 , I checked the message today . It got resolved . Thank you

**Comment by jxmorris12** [comment]
I'm glad!

**Comment by MartenBE** [comment]
> 
> 
> I faced this error while running tool.check function on a piece of text . Can anyone please guide me here ?

I am facing this error, how did you resolve this?

```
 * Serving Flask app 'auto-mail-checker.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Exception on / [POST]
Traceback (most recent call last):
  File "/home/martijn/git/auto-email-checker/lib64/python3.9/site-packages/language_tool_python/server.py", line 195, in _query_server
    with urlopen(url, data, self._TIMEOUT) as f:
  File "/usr/lib64/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib64/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martijn/git/auto-email-checker/lib64/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/martijn/git/auto-email-checker/lib64/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/martijn/git/auto-email-checker/lib64/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/martijn/git/auto-email-checker/lib64/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/martijn/git/auto-email-checker/auto-mail-checker.py", line 20, in root
    (errors, debug) = checker.check(email)
  File "/home/martijn/git/auto-email-checker/checker.py", line 145, in check
    self.check_correct_spelling(email, errors, debug, name)
  File "/home/martijn/git/auto-email-checker/checker.py", line 105, in check_correct_spelling
    matches = self.languagetool.check(email)
  File "/home/martijn/git/auto-email-checker/lib64/python3.9/site-packages/language_tool_python/server.py", line 109, in check
    response = self._query_server(url, self._encode(text))
  File "/home/martijn/git/auto-email-checker/lib64/python3.9/site-packages/language_tool_python/server.py", line 208, in _query_server
    raise LanguageToolError('{}: {}'.format(self._url, e))
language_tool_python.utils.LanguageToolError: http://127.0.0.1:8081/v2/: HTTP Error 500: Internal Server Error
127.0.0.1 - - [27/May/2021 00:00:32] "POST / HTTP/1.1" 500 -
```

**Comment by jxmorris12** [comment]
@MartenBE - looks like you're facing a different error (`HTTP Error 500: Internal Server Error`). Can you post the comments of `email` so I can try and reproduce your error? Also, it might be worth opening a separate issue (since this issue, #10, is about the 'timed out' error).

**Comment by MartenBE** [comment]
> 
> 
> @MartenBE - looks like you're facing a different error (`HTTP Error 500: Internal Server Error`). Can you post the comments of `email` so I can try and reproduce your error? Also, it might be worth opening a separate issue (since this issue, #10, is about the 'timed out' error).

Apparently, the `alternatives` command pointed my java installation to jdk 11 and not the latest. Pointing `alternatives` to the latest java installation did the trick. Everything works now

**Comment by jxmorris12** [comment]
@MartenBE how did you change `alternatives` to point to the correct version? I'd like to get this fix merged.

**Comment by MartenBE** [comment]
The `alternatives` command is provided by the distro (or installed manually through the package manager), so it is not a part of this project. A tutorial for it is available on https://blogs.igalia.com/dpino/2011/10/13/configuring-different-jdks-with-alternatives/ . I just selected the latest java installation using `sudo alternatives --config java`.

**Comment by jxmorris12** [comment]
Oh I see. I thought you were talking about some python library for some reason. I can add this info to the readme then.
