### ISSUE TITLE
Wrong detection of Java version on Mac 

### ISSUE THREAD

**Issue by yfyodorov** [jxmorris12/language_tool_python#6]
Hi
I've the following Java version
```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
```

When I tried to use language_tool_python, I've got the following error
```
Traceback (most recent call last):
  --- removed my function calls ---
  File "/Users/yfyodorov/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/language_tool_python/server.py", line 37, in __init__
    self._start_server_on_free_port()
  File "/Users/yfyodorov/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/language_tool_python/server.py", line 183, in _start_server_on_free_port
    cls._start_local_server()
  File "/Users/yfyodorov/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/language_tool_python/server.py", line 194, in _start_local_server
    download_lt()
  File "/Users/yfyodorov/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/language_tool_python/download_lt.py", line 133, in download_lt
    confirm_java_compatibility()
  File "/Users/yfyodorov/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/language_tool_python/download_lt.py", line 74, in confirm_java_compatibility
    raise SystemError('Detected java {}.{}. LanguageTool requires Java >= 8.'.format(major_version, minor_version))
SystemError: Detected java 1.8. LanguageTool requires Java >= 8.
```

From what I've seen in the code `parse_java_version` determined major version as 1 and minor as 8 instead of 8 and 0_112 (I supopose) which caused it to throw and error in `confirm_java_compatibility`.
I've tweaked the check to look at minor version for now and it looks like it is working now.

It seems version parser needs to be fixed to parse `java version "1.8.0_112"` correctly.

**Comment by jxmorris12** [comment]
Hey @yfyodorov -- thanks for explaining well and figuring out the fix already. I pushed a new version, `2.2.1`, so hopefully it'll work if you `pip install --upgrade`. Please do let me know.

PS. I think the issue is what's discussed here: https://softwareengineering.stackexchange.com/questions/175075/why-is-java-version-1-x-referred-to-as-java-x  Seems like java has some serious naming issues. Glad the fix is just to ignore the leading "1" though.

**Comment by yfyodorov** [comment]
Hi
Yes, it fixed the problem as far as I can tell. Thanks for the quick fix
