### ISSUE TITLE
ConnectionResetError encountered while multi threading

### ISSUE THREAD

**Issue by jkyndir** [jxmorris12/language_tool_python#66]
Help! 
When i use python's `concurrent.future.ThreadPoolExecutor` to concurrently run a large number of threads in 
parallel, the sript would throw the following error.

However, when i descrease the number of cucurrent threads to a number low enough, such errors can be avoided.

So, my question is, how can i avoid this error, when i want the script to run as many threads as my machine's hardware allows?

Any help or input would be much appreciated.

```
Traceback (most recent call last):
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\language_tool_python\server.py", line 218, in _query_server
    with requests.get(url, params=params, timeout=self._TIMEOUT) as response:
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 219, in <module>
    main()
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 213, in main
    ltCheck_col_in_xls(args.dir, args.col, args.lng)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 193, in ltCheck_col_in_xls
    future.result()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 182, in ltCheck_col_in_xl
    o_df = ltCheck_col_in_dfDict(lngTool, i_df_dicts, iStr_colNm)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 169, in ltCheck_col_in_dfDict
    ltCheckResult_df = ltCheck_col_in_df(lngTool, i_df, iStr_colNm)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 152, in ltCheck_col_in_df
    if f.result() is not None:
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 124, in ltCheck_col_in_row
    row_ltCheckResult_df = ltCheck(lngTool, iStr)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 81, in ltCheck
    matches = lngTool.check(iStr)
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\language_tool_python\server.py", line 129, in check
    response = self._query_server(url, self._create_params(text))
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\language_tool_python\server.py", line 229, in _query_server
    self._terminate_server()
  File "C:\Users\devJ\AppData\Local\Programs\Python\Python310\lib\site-packages\language_tool_python\server.py", line 309, in _terminate_server
    self._server.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

**Comment by jxmorris12** [comment]
@jkyndir My initial guess is that you're using too many threads to make too many concurrent requests to the server, which is (as far as I know) multithreaded. I think the better way to do it would be to initialize multiple servers instead of bombarding the single one. But I know that LanguageTool also takes a `maxCheckThreads` option (see the LT [HTTPServerConfig](https://languagetool.org/development/api/org/languagetool/server/HTTPServerConfig.html) documentation), so you could also try playing around with that? From a glance at the code, it looks like the [default number of threads in a single LanguageTool server](https://github.com/languagetool-org/languagetool/blob/master/languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java#L74) is 10.

**Comment by jkyndir** [comment]
> @jkyndir My initial guess is that you're using too many threads to make too many concurrent requests to the server, which is (as far as I know) multithreaded. I think the better way to do it would be to initialize multiple servers instead of bombarding the single one. But I know that LanguageTool also takes a `maxCheckThreads` option (see the LT [HTTPServerConfig](https://languagetool.org/development/api/org/languagetool/server/HTTPServerConfig.html) documentation), so you could also try playing around with that? From a glance at the code, it looks like the [default number of threads in a single LanguageTool server](https://github.com/languagetool-org/languagetool/blob/master/languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java#L74) is 10.

hey, man,

first of all, thank you so much for the response.

I tried your suggestion and divided the huge data load into different batches and creates a server instance for each of the batch.
But still, i would run into problems if the data to be processed is very huge.

The new error is as follows:
```
Traceback (most recent call last):
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\language_tool_python\server.py", line 218, in _query_server
    with requests.get(url, params=params, timeout=self._TIMEOUT) as response:
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 221, in <module>
    main()
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 216, in main
    ltCheck_col_in_xls(args.dir, args.col, args.lng)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 188, in ltCheck_col_in_xls
    ltCheck_col_in_xl(xlFlPth, iStr_colNm, lngCode)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 177, in ltCheck_col_in_xl
    o_df = ltCheck_col_in_dfDict(lngCode, i_df_dicts, iStr_colNm)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 159, in ltCheck_col_in_dfDict
    ltCheckResult_df = ltCheck_col_in_df(lngTool, batch_df, iStr_colNm)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 124, in ltCheck_col_in_df
    if f.result() is not None:
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 96, in ltCheck_col_in_row
    row_ltCheckResult_df = ltCheck(lngTool, iStr)
  File "D:\dev\jkyndir\Tech\Python\LingoCheck\LTCheck_on_xls.py", line 52, in ltCheck
    matches = lngTool.check(iStr)
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\language_tool_python\server.py", line 129, in check
    response = self._query_server(url, self._create_params(text))
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\language_tool_python\server.py", line 229, in _query_server
    self._terminate_server()
  File "C:\Users\dev_J\AppData\Local\Programs\Python\Python310\lib\site-packages\language_tool_python\server.py", line 309, in _terminate_server
    self._server.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

**Comment by jxmorris12** [comment]
feel free to reopen
